package Jframes;


import Classes.User;
import java.awt.Color;
import javax.swing.JPanel;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.LineNumberReader;
import java.text.MessageFormat;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author David
 */
public class AdminDashboard extends javax.swing.JFrame {

    User UC = new User();
    private DefaultTableModel tm;
    
    public AdminDashboard(){
    }
    public AdminDashboard(String pst, String id,String username,String email, int contact, String password,int icno){
        initComponents();
        
        UC.setUserID(id);
        UC.setUserRole(pst);
        UC.setUsername(username);
        UC.setEmailAddress(email);
        UC.setContactNo(contact);
        UC.setPassword(password);
        UC.setICNO(icno);
        
        Welcome.setText("Welcome back, " + username);
        Name.setText(username);
        
        autodisplay();
        autodisplay1();
        autodisplay2();
        countsupplier();
        countproductmanager();
        countstocklevel();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ControlPanel = new javax.swing.JPanel();
        RegistrationPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ProfilePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Viewalluser = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ProductPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ManageProduct = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        ViewCatalogue = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        AdminMainPanel = new javax.swing.JPanel();
        AdminDashboardPanel = new javax.swing.JLayeredPane();
        AdminMainDashboard = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProductManagerTable = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        Welcome = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Name = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        SupplierTable = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        LoginLog = new javax.swing.JTable();
        SupplierNumber = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ControlPanel.setBackground(new java.awt.Color(137, 171, 227));
        ControlPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegistrationPanel.setBackground(new java.awt.Color(116, 156, 222));
        RegistrationPanel.setForeground(new java.awt.Color(255, 255, 255));
        RegistrationPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrationPanelMouseClicked(evt);
            }
        });
        RegistrationPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Registration");
        RegistrationPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        ControlPanel.add(RegistrationPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 190, 60));

        ProfilePanel.setBackground(new java.awt.Color(157, 185, 232));
        ProfilePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfilePanelMouseClicked(evt);
            }
        });
        ProfilePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Manage Profile");
        ProfilePanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        ControlPanel.add(ProfilePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 190, 60));

        Viewalluser.setBackground(new java.awt.Color(157, 185, 232));
        Viewalluser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewalluserMouseClicked(evt);
            }
        });
        Viewalluser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(137, 171, 227));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("View all Users");
        Viewalluser.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        ControlPanel.add(Viewalluser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 190, 60));

        ProductPanel.setBackground(new java.awt.Color(157, 185, 232));
        ProductPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Product");
        ProductPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 90, 20));

        ControlPanel.add(ProductPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 190, 60));

        ManageProduct.setBackground(new java.awt.Color(157, 185, 232));
        ManageProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageProductMouseClicked(evt);
            }
        });
        ManageProduct.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Manage Product");
        ManageProduct.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 150, 20));

        ControlPanel.add(ManageProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 190, 60));

        ViewCatalogue.setBackground(new java.awt.Color(157, 185, 232));
        ViewCatalogue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewCatalogueMouseClicked(evt);
            }
        });
        ViewCatalogue.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("View Catalogue");
        ViewCatalogue.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 20));

        ControlPanel.add(ViewCatalogue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 190, 60));

        getContentPane().add(ControlPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 780));

        AdminMainPanel.setBackground(new java.awt.Color(204, 204, 204));
        AdminMainPanel.setForeground(new java.awt.Color(178, 200, 237));
        AdminMainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminDashboardPanel.setBackground(new java.awt.Color(252, 246, 245));
        AdminDashboardPanel.setLayout(new java.awt.CardLayout());

        AdminMainDashboard.setBackground(new java.awt.Color(204, 204, 204));
        AdminMainDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(174, 14, 54));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Product Manager");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 30));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 120, 40));

        AdminMainDashboard.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 140, 100));

        ProductManagerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Manger ID", "Username"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ProductManagerTable);

        AdminMainDashboard.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 280, 300));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Welcome.setEditable(false);
        Welcome.setBackground(new java.awt.Color(255, 255, 255));
        Welcome.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Welcome.setForeground(new java.awt.Color(0, 0, 0));
        Welcome.setText("Welcome back,");
        Welcome.setBorder(null);
        Welcome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WelcomeActionPerformed(evt);
            }
        });
        jPanel6.add(Welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, 30));
        jPanel6.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 260, 20));

        Name.setForeground(new java.awt.Color(0, 0, 0));
        jPanel6.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 130, 20));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("You are login as admin.");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, 160, -1));

        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("Sign Out?");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 40, 60, -1));

        AdminMainDashboard.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PicturesIcons/black-friday-logo-feature.jpg"))); // NOI18N
        AdminMainDashboard.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Promotion");
        AdminMainDashboard.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        SupplierTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supplier ID", "Username"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(SupplierTable);

        AdminMainDashboard.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 270, 300));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Overview");
        AdminMainDashboard.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        LoginLog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "Last Log In"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(LoginLog);

        AdminMainDashboard.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, 270, 300));

        SupplierNumber.setBackground(new java.awt.Color(165, 156, 148));
        SupplierNumber.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Suppliers");
        SupplierNumber.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 30));

        jLabel21.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SupplierNumber.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 100, 40));

        AdminMainDashboard.add(SupplierNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 140, 100));

        jPanel8.setBackground(new java.awt.Color(211, 46, 94));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Stock Level");
        jPanel8.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 30));

        jLabel24.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel8.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 120, 40));

        AdminMainDashboard.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, 140, 100));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Print PDF");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        AdminMainDashboard.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 445, 70, 20));

        AdminDashboardPanel.add(AdminMainDashboard, "card3");

        AdminMainPanel.add(AdminDashboardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 780));

        getContentPane().add(AdminMainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 910, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrationPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrationPanelMouseClicked
        RegisterForm RF = new RegisterForm();
        RF.setVisible(true);
        setColor(RegistrationPanel);
        resetColor(ProfilePanel);
        resetColor(Viewalluser);
        resetColor(ViewCatalogue);
        resetColor(Viewalluser);
    }//GEN-LAST:event_RegistrationPanelMouseClicked

    private void ProfilePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfilePanelMouseClicked
        String id = UC.getUserID();
        String username = UC.getUsername();
        String email = UC.getEmailAddress();
        String pst = UC.getUserRole();
        int contact = UC.getContactNo();
        int icno =UC.getICNO();
        String password = UC.getPassword();
        
        dispose();
        AdminProfile ap = new AdminProfile(pst,id,username,email,contact,password,icno);
        ap.setVisible(true);
        setColor(ProfilePanel);
        resetColor(RegistrationPanel);
        resetColor(ViewCatalogue);
        resetColor(Viewalluser);
    }//GEN-LAST:event_ProfilePanelMouseClicked

    private void ViewalluserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewalluserMouseClicked
        dispose();
        AdminManageUser amu = new AdminManageUser();
        amu.setVisible(true);
        setColor(Viewalluser);
        resetColor(RegistrationPanel);
        resetColor(ProfilePanel);
        resetColor(ViewCatalogue);
        resetColor(Viewalluser);
    }//GEN-LAST:event_ViewalluserMouseClicked

    private void ViewCatalogueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewCatalogueMouseClicked
        ViewCatalogue VC = new ViewCatalogue();
        VC.setVisible(true);
        setColor(Viewalluser);
        resetColor(RegistrationPanel);
        resetColor(ProfilePanel);
        resetColor(ViewCatalogue);
        resetColor(Viewalluser);
    }//GEN-LAST:event_ViewCatalogueMouseClicked

    private void ManageProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageProductMouseClicked
        ManageProductInformation Mpri = new ManageProductInformation("AD");
        Mpri.setVisible(true);
    }//GEN-LAST:event_ManageProductMouseClicked

    private void WelcomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WelcomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WelcomeActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        MessageFormat header = new MessageFormat("Login History");
        MessageFormat footer = new MessageFormat("");
        try{
            LoginLog.print(JTable.PrintMode.NORMAL, header, footer);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print", e.getMessage());
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param panel
     * @param args the command line arguments
     */
    
    private void autodisplay2(){                                                                        //display Login Log 
        try
        {
            tm = (DefaultTableModel)LoginLog.getModel();                                                                                   //use this table to display data
            BufferedReader br = new BufferedReader(new FileReader("Login Log.txt"));                                                             //read data from text file
            String line = "";
            while ((line = br.readLine()) != null) {     
                System.out.println(line);
                String[] data = line.split(",");                                                                                                   //check text file got data or not
                String[] nani = {data[1],data[3]};
                tm.addRow(nani);                                                                                                                   //add each line of data from text file to new row in table
            }
            br.close();                                                                                                                            //finish load data close reader
        }
        catch (IOException e)
        {
            e.printStackTrace();
        }
    }
    
    private void autodisplay1(){
          try
        {
            tm = (DefaultTableModel) ProductManagerTable.getModel();                                                                                   //use this table to display data
            BufferedReader br = new BufferedReader(new FileReader("ProductManager.txt"));                                                             //read data from text file
            String line = "";
            while ((line = br.readLine()) != null) {     
                System.out.println(line);
                String[] data = line.split(",");                                                                                                   //check text file got data or not
                String[] nani = {data[0],data[1]};
                tm.addRow(nani);                                                                                                                   //add each line of data from text file to new row in table
            }
            br.close();                                                                                                                            //finish load data close reader
        }
        catch (IOException e)
        {
            e.printStackTrace();
        }
    }                                                          
    
    private void autodisplay(){
        try
        {
            tm = (DefaultTableModel) SupplierTable.getModel();                                                                                   //use this table to display data
            BufferedReader br = new BufferedReader(new FileReader("Supplier.txt"));                                                             //read data from text file
            String line = "";
            while ((line = br.readLine()) != null) {     
                System.out.println(line);
                String[] data = line.split(",");                                                                                                   //check text file got data or not
                String[] nani = {data[0],data[1]};
                tm.addRow(nani);                                                                                                                   //add each line of data from text file to new row in table
            }
            br.close();                                                                                                                            //finish load data close reader
        }
        catch (IOException e)
        {
            e.printStackTrace();
        }
    }
    
    public void setColor(JPanel panel){
        panel.setBackground(new Color(116,156,222));
    }
    
    public void resetColor(JPanel panel){
        panel.setBackground(new Color(157,185,232));
    }
    public void switchPanels(JPanel panel) //Switch Panel
    {
        AdminDashboardPanel.removeAll();
        AdminDashboardPanel.add(panel);
        AdminDashboardPanel.repaint();
        AdminDashboardPanel.revalidate();
    }  
    
    private void countsupplier(){
        try{
            File file = new File("Supplier.txt");
            if(file.exists()){
                FileReader fr = new FileReader(file);
                LineNumberReader LNR = new LineNumberReader(fr);
                int linenumber = 0;
                while(LNR.readLine() != null){
                 linenumber++;
                }
                jLabel21.setText(String.valueOf(linenumber));
                fr.close();
            }
            else{
                JOptionPane.showMessageDialog(null,"File not exist.");
            }
        } catch (IOException e) { 
        }
    }
    
    private void countproductmanager(){
        try{
            File file = new File("ProductManager.txt");
            if(file.exists()){
                FileReader fr = new FileReader(file);
                LineNumberReader LNR = new LineNumberReader(fr);
                int linenumber = 0;
                while(LNR.readLine() != null){
                 linenumber++;
                }
                jLabel12.setText(String.valueOf(linenumber));
                fr.close();
            }
            else{
                JOptionPane.showMessageDialog(null,"File not exist.");
            }
        } catch (IOException e) { 
        }
    }
    
    private void countstocklevel(){
         try{
            FileReader fr = new FileReader("ProductData.txt");
            Scanner sc = new Scanner(fr);
            int sum = 0;
            while(sc.hasNext()){
                String line = sc.nextLine();
                String [] data = line.split(",");
                sum = sum + Integer.parseInt(data[6].trim());
            }
            jLabel24.setText(String.valueOf(sum));
            sc.close();
        } catch (IOException e) { 
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane AdminDashboardPanel;
    private javax.swing.JPanel AdminMainDashboard;
    private javax.swing.JPanel AdminMainPanel;
    private javax.swing.JPanel ControlPanel;
    private javax.swing.JTable LoginLog;
    private javax.swing.JPanel ManageProduct;
    private javax.swing.JLabel Name;
    private javax.swing.JTable ProductManagerTable;
    private javax.swing.JPanel ProductPanel;
    private javax.swing.JPanel ProfilePanel;
    private javax.swing.JPanel RegistrationPanel;
    private javax.swing.JPanel SupplierNumber;
    private javax.swing.JTable SupplierTable;
    private javax.swing.JPanel ViewCatalogue;
    private javax.swing.JPanel Viewalluser;
    private javax.swing.JTextField Welcome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
