/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jframes;

import Classes.ProductManager;
import Classes.User;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.Scanner;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author David
 */
public class ModifyProductInfo extends javax.swing.JFrame {
    boolean CheckEmpty;
    boolean checkInput;
    String TypeofUser;
    /**
     * Creates new form ModifyProductInfo
     */
    public ModifyProductInfo() {
        initComponents();
        
    }

    public ModifyProductInfo(String carry,String UserType) {
        initComponents();
        setLocationRelativeTo(null);
        UserType = TypeofUser;
        ModifyProductIDTextBox.setEditable(false);
        ComboBoxItems();
        ComboBoxSupplier();
        ModifyProductIDTextBox.setText(carry);
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ModifyPNameTextBox = new javax.swing.JTextField();
        ModifyPPriceTextBox = new javax.swing.JTextField();
        ModifyPDescTextBox = new javax.swing.JTextField();
        PMModifyProductButton = new javax.swing.JButton();
        ModifyPCatComboBox = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        ModifyProductIDTextBox = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        ModifyPStockTextBox = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        ModifySupplierComboBox = new javax.swing.JComboBox<>();
        Cancelbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(252, 246, 245));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(252, 118, 106));
        jLabel12.setText("NewProductName:");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(252, 118, 106));
        jLabel13.setText("NewProductPrice:");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(252, 118, 106));
        jLabel14.setText("NewProductCategory:");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(252, 118, 106));
        jLabel15.setText("NewProductDescription:");

        ModifyPNameTextBox.setBackground(new java.awt.Color(204, 204, 204));
        ModifyPNameTextBox.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        ModifyPPriceTextBox.setBackground(new java.awt.Color(204, 204, 204));
        ModifyPPriceTextBox.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        ModifyPDescTextBox.setBackground(new java.awt.Color(204, 204, 204));
        ModifyPDescTextBox.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        PMModifyProductButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PMModifyProductButton.setText("Confirm Modification");
        PMModifyProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PMModifyProductButtonActionPerformed(evt);
            }
        });

        ModifyPCatComboBox.setBackground(new java.awt.Color(204, 204, 204));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(252, 118, 106));
        jLabel16.setText("ProductID:");

        ModifyProductIDTextBox.setBackground(new java.awt.Color(204, 204, 204));
        ModifyProductIDTextBox.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(252, 118, 106));
        jLabel17.setText("NewStock:");

        ModifyPStockTextBox.setBackground(new java.awt.Color(204, 204, 204));
        ModifyPStockTextBox.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(252, 118, 106));
        jLabel18.setText("NewSupplier:");

        ModifySupplierComboBox.setBackground(new java.awt.Color(204, 204, 204));

        Cancelbutton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Cancelbutton.setText("Cancel");
        Cancelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ModifyPCatComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ModifyProductIDTextBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ModifyPNameTextBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ModifyPDescTextBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ModifyPStockTextBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ModifySupplierComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(ModifyPPriceTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(PMModifyProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(Cancelbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ModifyProductIDTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ModifyPNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ModifyPPriceTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ModifyPCatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ModifyPDescTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ModifyPStockTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ModifySupplierComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PMModifyProductButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cancelbutton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PMModifyProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PMModifyProductButtonActionPerformed
        ChkEmptyValidation();
        checkinputint();
        ManageProductInformation PMI  = new ManageProductInformation("PM");
        if (CheckEmpty == true && checkInput == true){
            try
            {
                FileInputStream fstream = new FileInputStream("ProductData.txt");
                BufferedReader br = new BufferedReader(new InputStreamReader(fstream));
                String line = "";
                StringBuilder data = new StringBuilder();
                while ((line = br.readLine()) != null)
                {
                    String values[] = line.split(",");
                    if (values.length>0) {
                        if (values[0].equals(ModifyProductIDTextBox.getText())) {
                            String dataRow = ModifyProductIDTextBox.getText() + "," + ModifyPNameTextBox.getText() + "," + ModifyPPriceTextBox.getText() + ","
                            + ModifyPCatComboBox.getSelectedItem() + "," + ModifyPDescTextBox.getText() + "," + ModifyPStockTextBox.getText() + "," + ModifySupplierComboBox.getSelectedItem();
                            data.append(dataRow);
                            data.append("\n");
                        }
                        else
                        {
                            data.append(line);
                            data.append("\n");
                        }
                    }
                }
                fstream.close();
                FileWriter fw = new FileWriter("ProductData.txt");
                BufferedWriter bw = new BufferedWriter(fw);
                bw.write(data.toString());
                bw.close();
                fw.close();
                JOptionPane.showMessageDialog(null,"Product Modified.");

            }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null,e.toString());
            } 
        }
        this.dispose();
    }//GEN-LAST:event_PMModifyProductButtonActionPerformed

    private void CancelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelbuttonActionPerformed

           this.dispose();
        
    }//GEN-LAST:event_CancelbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    private void ComboBoxSupplier(){
    DefaultComboBoxModel SupplierModel = new DefaultComboBoxModel();
    String SupplierPath = ("Supplier.txt");
    File SupplierFile = new File(SupplierPath);
    try (Scanner in = new Scanner(SupplierFile)){
        in.useDelimiter("[,\n]");
        while (in.hasNextLine()) {
            String ID;
            ID = in.next();
            in.next();
            in.next();
            in.next();
            in.next();
            in.next();
            in.next();
            in.nextLine();
            SupplierModel.addElement(ID);
            ModifySupplierComboBox.setModel(SupplierModel);
        }
    in.close();
    } catch (FileNotFoundException ex){
        JOptionPane.showMessageDialog(null,"File Path not Found.");
    }
}
private void ComboBoxItems(){
    DefaultComboBoxModel CategoryModel = new DefaultComboBoxModel();
    String CategoryItemPath = ("ProductCategoryData.txt");
    File CategoryItemFile = new File(CategoryItemPath);
    try (Scanner in = new Scanner(CategoryItemFile)){
        in.useDelimiter("[,\n]");
        while (in.hasNextLine()) {
            String line;
            line = in.nextLine();
            CategoryModel.addElement(line);
            ModifyPCatComboBox.setModel(CategoryModel);
        }
    in.close();
    } catch (FileNotFoundException ex){
        JOptionPane.showMessageDialog(null,"File Path not Found.");
    }
}
    private boolean ChkEmptyValidation(){
        if (ModifyPNameTextBox.getText() == null || ModifyPPriceTextBox.getText() == null || ModifyPCatComboBox.getSelectedItem() == null || ModifyPDescTextBox.getText() == null){
            CheckEmpty = false;
            return false;
        }
        else{
            CheckEmpty = true;
            return true;
        }
        
    }
        public boolean checkinputint(){
        checkInput = true;
        try {
            Integer.parseInt(ModifyPStockTextBox.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null,"Stock must be Integer.");
            checkInput = false;
            return false;
        }
        return true;
    }
        
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelbutton;
    public javax.swing.JComboBox<String> ModifyPCatComboBox;
    private javax.swing.JTextField ModifyPDescTextBox;
    private javax.swing.JTextField ModifyPNameTextBox;
    private javax.swing.JTextField ModifyPPriceTextBox;
    private javax.swing.JTextField ModifyPStockTextBox;
    private javax.swing.JTextField ModifyProductIDTextBox;
    public javax.swing.JComboBox<String> ModifySupplierComboBox;
    private javax.swing.JButton PMModifyProductButton;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
