/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jframes;
import Classes.ProductManager;
import Jframes.PMDashboard;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import javax.swing.JOptionPane;
/**
 *
 * @author David
 */
public class ModifyCategoryInformation extends javax.swing.JFrame {
    boolean CheckCatEmpty = true;
    ProductManager PM = new ProductManager();
    /**
     * Creates new form ModifyCategoryInformation
     */
    public ModifyCategoryInformation() {
        initComponents();
    }
    public ModifyCategoryInformation(String CatCarry, String id) {
        PM.setUserID(id);
        initComponents();
        setLocationRelativeTo(null);
        ModifyCatIDTextBox.setText(CatCarry);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        ModifyCatIDTextBox = new javax.swing.JTextField();
        ModifyCatNameTextBox = new javax.swing.JTextField();
        PMModifyProductButton = new javax.swing.JButton();
        PMCatCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(252, 246, 245));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(252, 118, 106));
        jLabel16.setText("CategoryID:");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(252, 118, 106));
        jLabel17.setText("CategoryName:");

        ModifyCatIDTextBox.setEditable(false);
        ModifyCatIDTextBox.setBackground(new java.awt.Color(204, 204, 204));
        ModifyCatIDTextBox.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        ModifyCatNameTextBox.setBackground(new java.awt.Color(204, 204, 204));
        ModifyCatNameTextBox.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        PMModifyProductButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PMModifyProductButton.setText("Confirm Modification");
        PMModifyProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PMModifyProductButtonActionPerformed(evt);
            }
        });

        PMCatCancel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PMCatCancel.setText("Cancel");
        PMCatCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PMCatCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(PMCatCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel16)
                        .addComponent(jLabel17)
                        .addComponent(ModifyCatIDTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addComponent(ModifyCatNameTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addComponent(PMModifyProductButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ModifyCatIDTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ModifyCatNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PMModifyProductButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PMCatCancel)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PMModifyProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PMModifyProductButtonActionPerformed
        String id = PM.getUserID();
        PMDashboard pm = new PMDashboard(id);
        
        CatEmptyValidation();

        if (CheckCatEmpty == true){
            try
            {
                FileInputStream fstream = new FileInputStream("ProductCategoryData.txt");
                BufferedReader br = new BufferedReader(new InputStreamReader(fstream));
                String line = "";
                StringBuilder data = new StringBuilder();
                while ((line = br.readLine()) != null)
                {
                    String values[] = line.split(",");
                    if (values.length>0) {
                        if (values[0].equals(ModifyCatIDTextBox.getText())) {
                            String dataRow = ModifyCatIDTextBox.getText() + "," + ModifyCatNameTextBox.getText();
                            data.append(dataRow);
                            data.append("\n");
                        }
                        else
                        {
                            data.append(line);
                            data.append("\n");
                        }
                    }
                }
                fstream.close();
                FileWriter fw = new FileWriter("ProductCategoryData.txt");
                BufferedWriter bw = new BufferedWriter(fw);
                bw.write(data.toString());
                bw.close();
                fw.close();
                JOptionPane.showMessageDialog(null,"Category Modified.");
                pm.clearCategoryTable();
                pm.displayCategoryTable();
            }
            catch(FileNotFoundException e)
            {
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null,"Category unable to be modified.");
            }
        }
        pm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PMModifyProductButtonActionPerformed

    private void PMCatCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PMCatCancelActionPerformed
        String id = PM.getUserID();
        PMDashboard pm = new PMDashboard(id);
        pm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PMCatCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ModifyCatIDTextBox;
    private javax.swing.JTextField ModifyCatNameTextBox;
    private javax.swing.JButton PMCatCancel;
    private javax.swing.JButton PMModifyProductButton;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private boolean CatEmptyValidation(){
        CheckCatEmpty = true;
        if (ModifyCatNameTextBox.getText() == null) {
            JOptionPane.showMessageDialog(null, "Please Fill in Name TextBox.");
            return false;
        }
        return true;
    }



}
