package Jframes;




import Classes.Product;
import Classes.ProductManager;
import Jframes.RegisterForm;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import javax.swing.JPanel;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.util.Scanner;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class PMDashboard extends javax.swing.JFrame {
boolean checkID;
boolean checkempty;
boolean checkpassword;
ProductManager PM = new ProductManager();

    /**
     * Creates new form PMDashboard
     * @param id
     */
    public PMDashboard(String id) {
        initComponents();
        PM.setUserID(id);
        PMIDTextBox.setText(id);
        setLocationRelativeTo(null);
        PMIDTextBox.setEditable(false);
        PMINTextBox.setEditable(false);
        getProfileDetails();
        clearCategoryTable();
        displayCategoryTable();
    }

    public void switchPanels(JPanel panel) //Switch Panel
    {
        MainPanel.removeAll();
        MainPanel.add(panel);
        MainPanel.repaint();
        MainPanel.revalidate();
    }   
    public static void Findstr(){ //Search
        File file = new File ("ProductData.txt");
        
        Scanner kb = new Scanner(System.in);
        
    }
    void clearCategoryTable(){
        DefaultTableModel categorymodel = (DefaultTableModel)CategoryTable.getModel();
        categorymodel.setRowCount(0);
    }
    void displayCategoryTable(){
      DefaultTableModel model = (DefaultTableModel)CategoryTable.getModel();
      String line;
      BufferedReader r;
      try{
          File f = new File("ProductCategoryData.txt");
          r = new BufferedReader(new FileReader(f));
          while((line = r.readLine()) != null)
          {
              model.addRow(line.split(","));
          }
          r.close();
      }catch(Exception e){
          System.out.println(e);
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jComboBox1 = new javax.swing.JComboBox<>();
        jToolBar1 = new javax.swing.JToolBar();
        jMenuItem1 = new javax.swing.JMenuItem();
        ToolbarPanel = new javax.swing.JPanel();
        PMManageButton = new javax.swing.JLabel();
        PMDashboardCloseButton = new javax.swing.JLabel();
        PMDashboardMinimizeButton = new javax.swing.JLabel();
        PMProfileButton = new javax.swing.JLabel();
        MainPanel = new javax.swing.JLayeredPane();
        PMProfileManagementPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        UsernameLabel5 = new javax.swing.JLabel();
        UsernameLabel9 = new javax.swing.JLabel();
        UsernameLabel13 = new javax.swing.JLabel();
        PMIDTextBox = new javax.swing.JTextField();
        PMEditProfileButton = new javax.swing.JButton();
        PMINTextBox = new javax.swing.JTextField();
        PMUsernameTextBox = new javax.swing.JTextField();
        PMContactTextBox = new javax.swing.JTextField();
        PMEmailTextBox = new javax.swing.JTextField();
        UsernameLabel6 = new javax.swing.JLabel();
        PMPasswordTextBox = new javax.swing.JTextField();
        UsernameLabel7 = new javax.swing.JLabel();
        PMConfirmPassword = new javax.swing.JTextField();
        PMManageProductCategoryPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        PMCategoryIDTextBox = new javax.swing.JTextField();
        PMCategoryNameTextBox = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        CategoryTable = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        AddCategoryButton = new javax.swing.JButton();
        ModifyCategoryButton = new javax.swing.JButton();
        DeleteCategoryButton = new javax.swing.JButton();
        ExtendedPanel = new javax.swing.JPanel();
        PMManagePanel = new javax.swing.JPanel();
        PMManageProductButton = new javax.swing.JLabel();
        PMManageCatalogueButton = new javax.swing.JLabel();
        PMProfileButtonPanel = new javax.swing.JPanel();
        PMProfileSettingsButton = new javax.swing.JLabel();
        PMSignoutButton = new javax.swing.JLabel();
        PMManageProductExtPanel = new javax.swing.JPanel();
        PMManageProductInfo = new javax.swing.JLabel();
        PMManageProductCategory = new javax.swing.JLabel();

        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Manage Profile");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(252, 118, 106));
        jLabel8.setText("User ID:");

        jScrollPane1.setViewportView(jEditorPane1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jToolBar1.setRollover(true);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(252, 246, 245));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ToolbarPanel.setBackground(new java.awt.Color(137, 171, 227));
        ToolbarPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ToolbarPanel.setPreferredSize(new java.awt.Dimension(681, 41));
        ToolbarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PMManageButton.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        PMManageButton.setForeground(new java.awt.Color(252, 246, 245));
        PMManageButton.setText("Manage");
        PMManageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PMManageButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PMManageButtonMouseExited(evt);
            }
        });
        ToolbarPanel.add(PMManageButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 65, 41));

        PMDashboardCloseButton.setBackground(new java.awt.Color(252, 246, 245));
        PMDashboardCloseButton.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        PMDashboardCloseButton.setForeground(new java.awt.Color(252, 246, 245));
        PMDashboardCloseButton.setText("X");
        PMDashboardCloseButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PMDashboardCloseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PMDashboardCloseButtonMouseClicked(evt);
            }
        });
        ToolbarPanel.add(PMDashboardCloseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 11, -1, -1));

        PMDashboardMinimizeButton.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        PMDashboardMinimizeButton.setForeground(new java.awt.Color(252, 246, 245));
        PMDashboardMinimizeButton.setText("_");
        PMDashboardMinimizeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PMDashboardMinimizeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PMDashboardMinimizeButtonMouseClicked(evt);
            }
        });
        ToolbarPanel.add(PMDashboardMinimizeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 11, -1, -1));

        PMProfileButton.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        PMProfileButton.setForeground(new java.awt.Color(252, 246, 245));
        PMProfileButton.setText("Profile");
        PMProfileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PMProfileButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PMProfileButtonMouseExited(evt);
            }
        });
        ToolbarPanel.add(PMProfileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 1, -1, 40));

        getContentPane().add(ToolbarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, -1));

        MainPanel.setBackground(new java.awt.Color(252, 246, 245));
        MainPanel.setLayout(new java.awt.CardLayout());

        PMProfileManagementPanel.setBackground(new java.awt.Color(252, 246, 245));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(252, 118, 106));
        jLabel6.setText("Profile Management");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(252, 118, 106));
        jLabel9.setText("User ID:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(252, 118, 106));
        jLabel5.setText("Username:");

        UsernameLabel5.setBackground(new java.awt.Color(203, 206, 145));
        UsernameLabel5.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        UsernameLabel5.setForeground(new java.awt.Color(252, 118, 106));
        UsernameLabel5.setText("Identification Number:");

        UsernameLabel9.setBackground(new java.awt.Color(203, 206, 145));
        UsernameLabel9.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        UsernameLabel9.setForeground(new java.awt.Color(252, 118, 106));
        UsernameLabel9.setText("Contact Number:");

        UsernameLabel13.setBackground(new java.awt.Color(203, 206, 145));
        UsernameLabel13.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        UsernameLabel13.setForeground(new java.awt.Color(252, 118, 106));
        UsernameLabel13.setText("Email Address:");

        PMIDTextBox.setBackground(new java.awt.Color(204, 204, 204));
        PMIDTextBox.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        PMIDTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PMIDTextBoxActionPerformed(evt);
            }
        });

        PMEditProfileButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PMEditProfileButton.setText("Modify");
        PMEditProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PMEditProfileButtonActionPerformed(evt);
            }
        });

        PMINTextBox.setBackground(new java.awt.Color(204, 204, 204));
        PMINTextBox.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        PMUsernameTextBox.setBackground(new java.awt.Color(204, 204, 204));
        PMUsernameTextBox.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        PMContactTextBox.setBackground(new java.awt.Color(204, 204, 204));
        PMContactTextBox.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        PMEmailTextBox.setBackground(new java.awt.Color(204, 204, 204));
        PMEmailTextBox.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        UsernameLabel6.setBackground(new java.awt.Color(203, 206, 145));
        UsernameLabel6.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        UsernameLabel6.setForeground(new java.awt.Color(252, 118, 106));
        UsernameLabel6.setText("Confirm Password:");

        PMPasswordTextBox.setBackground(new java.awt.Color(204, 204, 204));
        PMPasswordTextBox.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        UsernameLabel7.setBackground(new java.awt.Color(203, 206, 145));
        UsernameLabel7.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        UsernameLabel7.setForeground(new java.awt.Color(252, 118, 106));
        UsernameLabel7.setText("Password:");

        PMConfirmPassword.setBackground(new java.awt.Color(204, 204, 204));
        PMConfirmPassword.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        javax.swing.GroupLayout PMProfileManagementPanelLayout = new javax.swing.GroupLayout(PMProfileManagementPanel);
        PMProfileManagementPanel.setLayout(PMProfileManagementPanelLayout);
        PMProfileManagementPanelLayout.setHorizontalGroup(
            PMProfileManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PMProfileManagementPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PMProfileManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PMProfileManagementPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(PMProfileManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PMProfileManagementPanelLayout.createSequentialGroup()
                                .addComponent(PMEmailTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PMProfileManagementPanelLayout.createSequentialGroup()
                                .addGroup(PMProfileManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6)
                                    .addGroup(PMProfileManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PMProfileManagementPanelLayout.createSequentialGroup()
                                            .addGroup(PMProfileManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel9)
                                                .addComponent(PMIDTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(36, 36, 36)
                                            .addGroup(PMProfileManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(PMINTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(UsernameLabel5)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PMProfileManagementPanelLayout.createSequentialGroup()
                                            .addGroup(PMProfileManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5)
                                                .addComponent(PMUsernameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                            .addGroup(PMProfileManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(PMContactTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(UsernameLabel9)))))
                                .addGap(258, 258, 258))))
                    .addGroup(PMProfileManagementPanelLayout.createSequentialGroup()
                        .addGroup(PMProfileManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UsernameLabel13)
                            .addGroup(PMProfileManagementPanelLayout.createSequentialGroup()
                                .addGroup(PMProfileManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PMPasswordTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UsernameLabel7))
                                .addGap(58, 58, 58)
                                .addGroup(PMProfileManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UsernameLabel6)
                                    .addComponent(PMConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(230, Short.MAX_VALUE))
                    .addGroup(PMProfileManagementPanelLayout.createSequentialGroup()
                        .addComponent(PMEditProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        PMProfileManagementPanelLayout.setVerticalGroup(
            PMProfileManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PMProfileManagementPanelLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PMProfileManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernameLabel5))
                .addGroup(PMProfileManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PMProfileManagementPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(UsernameLabel9))
                    .addGroup(PMProfileManagementPanelLayout.createSequentialGroup()
                        .addGroup(PMProfileManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PMIDTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PMINTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PMProfileManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PMUsernameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PMContactTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(UsernameLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PMEmailTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PMProfileManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernameLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PMProfileManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PMPasswordTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PMConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PMEditProfileButton)
                .addContainerGap(329, Short.MAX_VALUE))
        );

        MainPanel.add(PMProfileManagementPanel, "card2");

        PMManageProductCategoryPanel.setBackground(new java.awt.Color(252, 246, 245));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(252, 118, 106));
        jLabel15.setText("Products In the Category");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(252, 118, 106));
        jLabel17.setText("CategoryID:");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(252, 118, 106));
        jLabel18.setText("CategoryName:");

        PMCategoryIDTextBox.setEditable(false);
        PMCategoryIDTextBox.setBackground(new java.awt.Color(204, 204, 204));
        PMCategoryIDTextBox.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        PMCategoryIDTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PMCategoryIDTextBoxActionPerformed(evt);
            }
        });
        PMCategoryIDTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PMCategoryIDTextBoxKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PMCategoryIDTextBoxKeyTyped(evt);
            }
        });

        PMCategoryNameTextBox.setBackground(new java.awt.Color(204, 204, 204));
        PMCategoryNameTextBox.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        PMCategoryNameTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PMCategoryNameTextBoxActionPerformed(evt);
            }
        });
        PMCategoryNameTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PMCategoryNameTextBoxKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PMCategoryNameTextBoxKeyTyped(evt);
            }
        });

        CategoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CategoryID", "CategoryName"
            }
        ));
        CategoryTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CategoryTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(CategoryTable);

        jLabel21.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(252, 118, 106));
        jLabel21.setText("Manage Categories");

        AddCategoryButton.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        AddCategoryButton.setText("Add Category");
        AddCategoryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddCategoryButtonMouseClicked(evt);
            }
        });
        AddCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCategoryButtonActionPerformed(evt);
            }
        });

        ModifyCategoryButton.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        ModifyCategoryButton.setText("Modify Category");
        ModifyCategoryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModifyCategoryButtonMouseClicked(evt);
            }
        });
        ModifyCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyCategoryButtonActionPerformed(evt);
            }
        });

        DeleteCategoryButton.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        DeleteCategoryButton.setText("Delete Category");
        DeleteCategoryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteCategoryButtonMouseClicked(evt);
            }
        });
        DeleteCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteCategoryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PMManageProductCategoryPanelLayout = new javax.swing.GroupLayout(PMManageProductCategoryPanel);
        PMManageProductCategoryPanel.setLayout(PMManageProductCategoryPanelLayout);
        PMManageProductCategoryPanelLayout.setHorizontalGroup(
            PMManageProductCategoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PMManageProductCategoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PMManageProductCategoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PMManageProductCategoryPanelLayout.createSequentialGroup()
                        .addGroup(PMManageProductCategoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                            .addGroup(PMManageProductCategoryPanelLayout.createSequentialGroup()
                                .addGroup(PMManageProductCategoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(PMCategoryIDTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PMCategoryNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DeleteCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PMManageProductCategoryPanelLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PMManageProductCategoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ModifyCategoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AddCategoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(22, 22, 22))))
            .addGroup(PMManageProductCategoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PMManageProductCategoryPanelLayout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jLabel21)
                    .addContainerGap(408, Short.MAX_VALUE)))
        );
        PMManageProductCategoryPanelLayout.setVerticalGroup(
            PMManageProductCategoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PMManageProductCategoryPanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PMCategoryIDTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PMManageProductCategoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PMCategoryNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteCategoryButton))
                .addGap(11, 11, 11)
                .addComponent(ModifyCategoryButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PMManageProductCategoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(AddCategoryButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
            .addGroup(PMManageProductCategoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PMManageProductCategoryPanelLayout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jLabel21)
                    .addContainerGap(569, Short.MAX_VALUE)))
        );

        MainPanel.add(PMManageProductCategoryPanel, "card4");

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 650, 620));

        ExtendedPanel.setBackground(new java.awt.Color(252, 246, 245));
        ExtendedPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PMManagePanel.setBackground(new java.awt.Color(137, 171, 227));
        PMManagePanel.setMinimumSize(new java.awt.Dimension(160, 130));
        PMManagePanel.setName(""); // NOI18N
        PMManagePanel.setPreferredSize(new java.awt.Dimension(0, 0));
        PMManagePanel.setRequestFocusEnabled(false);
        PMManagePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PMManagePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PMManagePanelMouseExited(evt);
            }
        });

        PMManageProductButton.setBackground(new java.awt.Color(252, 246, 245));
        PMManageProductButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PMManageProductButton.setForeground(new java.awt.Color(252, 246, 245));
        PMManageProductButton.setText("Manage Product         >");
        PMManageProductButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PMManageProductButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PMManageProductButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PMManageProductButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PMManageProductButtonMouseExited(evt);
            }
        });

        PMManageCatalogueButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PMManageCatalogueButton.setForeground(new java.awt.Color(252, 246, 245));
        PMManageCatalogueButton.setText("Manage Catalogue");
        PMManageCatalogueButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PMManageCatalogueButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PMManageCatalogueButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PMManageCatalogueButtonMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout PMManagePanelLayout = new javax.swing.GroupLayout(PMManagePanel);
        PMManagePanel.setLayout(PMManagePanelLayout);
        PMManagePanelLayout.setHorizontalGroup(
            PMManagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PMManagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PMManagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PMManageCatalogueButton)
                    .addComponent(PMManageProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PMManagePanelLayout.setVerticalGroup(
            PMManagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PMManagePanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(PMManageProductButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PMManageCatalogueButton)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        ExtendedPanel.add(PMManagePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        PMProfileButtonPanel.setBackground(new java.awt.Color(137, 171, 227));
        PMProfileButtonPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PMProfileButtonPanel.setPreferredSize(new java.awt.Dimension(0, 0));
        PMProfileButtonPanel.setRequestFocusEnabled(false);
        PMProfileButtonPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PMProfileButtonPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PMProfileButtonPanelMouseExited(evt);
            }
        });
        PMProfileButtonPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PMProfileSettingsButton.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        PMProfileSettingsButton.setForeground(new java.awt.Color(252, 246, 245));
        PMProfileSettingsButton.setText("Profile Settings");
        PMProfileSettingsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PMProfileSettingsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PMProfileSettingsButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PMProfileSettingsButtonMouseEntered(evt);
            }
        });
        PMProfileButtonPanel.add(PMProfileSettingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, -1));

        PMSignoutButton.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        PMSignoutButton.setForeground(new java.awt.Color(252, 246, 245));
        PMSignoutButton.setText("Sign Out");
        PMSignoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PMSignoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PMSignoutButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PMSignoutButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PMSignoutButtonMouseExited(evt);
            }
        });
        PMProfileButtonPanel.add(PMSignoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 100, -1));

        ExtendedPanel.add(PMProfileButtonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 150, -1));

        PMManageProductExtPanel.setBackground(new java.awt.Color(137, 171, 227));
        PMManageProductExtPanel.setPreferredSize(new java.awt.Dimension(0, 0));
        PMManageProductExtPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PMManageProductExtPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PMManageProductExtPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PMManageProductExtPanelMouseExited(evt);
            }
        });

        PMManageProductInfo.setBackground(new java.awt.Color(252, 246, 245));
        PMManageProductInfo.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PMManageProductInfo.setForeground(new java.awt.Color(252, 246, 245));
        PMManageProductInfo.setText("Product Information");
        PMManageProductInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PMManageProductInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PMManageProductInfoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PMManageProductInfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PMManageProductInfoMouseExited(evt);
            }
        });

        PMManageProductCategory.setBackground(new java.awt.Color(252, 246, 245));
        PMManageProductCategory.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        PMManageProductCategory.setForeground(new java.awt.Color(252, 246, 245));
        PMManageProductCategory.setText("Product Category");
        PMManageProductCategory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PMManageProductCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PMManageProductCategoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PMManageProductCategoryMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout PMManageProductExtPanelLayout = new javax.swing.GroupLayout(PMManageProductExtPanel);
        PMManageProductExtPanel.setLayout(PMManageProductExtPanelLayout);
        PMManageProductExtPanelLayout.setHorizontalGroup(
            PMManageProductExtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PMManageProductExtPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PMManageProductExtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PMManageProductCategory)
                    .addComponent(PMManageProductInfo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PMManageProductExtPanelLayout.setVerticalGroup(
            PMManageProductExtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PMManageProductExtPanelLayout.createSequentialGroup()
                .addComponent(PMManageProductInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PMManageProductCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        ExtendedPanel.add(PMManageProductExtPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 110, -1));

        getContentPane().add(ExtendedPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 650, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PMManageButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PMManageButtonMouseEntered
        PMManagePanel.setSize (170,80);
    }//GEN-LAST:event_PMManageButtonMouseEntered

    private void PMManageButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PMManageButtonMouseExited
        PMManagePanel.setSize (0,0);
    }//GEN-LAST:event_PMManageButtonMouseExited

    private void PMDashboardCloseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PMDashboardCloseButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_PMDashboardCloseButtonMouseClicked

    private void PMDashboardMinimizeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PMDashboardMinimizeButtonMouseClicked
        this.setState(RegisterForm.ICONIFIED);
    }//GEN-LAST:event_PMDashboardMinimizeButtonMouseClicked

    private void PMProfileButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PMProfileButtonMouseEntered
        PMProfileButtonPanel.setSize (140, 80);
    }//GEN-LAST:event_PMProfileButtonMouseEntered

    private void PMProfileButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PMProfileButtonMouseExited
        PMProfileButtonPanel.setSize (0, 0);
    }//GEN-LAST:event_PMProfileButtonMouseExited

    private void PMManagePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PMManagePanelMouseExited
        PMManagePanel.setSize (0,0);
    }//GEN-LAST:event_PMManagePanelMouseExited

    private void PMManagePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PMManagePanelMouseEntered
        PMManagePanel.setSize (170,80);
    }//GEN-LAST:event_PMManagePanelMouseEntered

    private void PMManageCatalogueButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PMManageCatalogueButtonMouseEntered
        PMManagePanel.setSize (170,80);
    }//GEN-LAST:event_PMManageCatalogueButtonMouseEntered

    private void PMManageProductButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PMManageProductButtonMouseEntered
        PMManagePanel.setSize (170,80);
        PMManageProductExtPanel.setSize (150,70);
    }//GEN-LAST:event_PMManageProductButtonMouseEntered

    private void PMManageProductButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PMManageProductButtonMouseClicked

    }//GEN-LAST:event_PMManageProductButtonMouseClicked

    private void PMProfileButtonPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PMProfileButtonPanelMouseExited
        PMProfileButtonPanel.setSize (0, 0);
    }//GEN-LAST:event_PMProfileButtonPanelMouseExited

    private void PMProfileButtonPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PMProfileButtonPanelMouseEntered
        PMProfileButtonPanel.setSize (140, 80);
    }//GEN-LAST:event_PMProfileButtonPanelMouseEntered

    private void PMProfileSettingsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PMProfileSettingsButtonMouseClicked
        switchPanels(PMProfileManagementPanel);
    }//GEN-LAST:event_PMProfileSettingsButtonMouseClicked

    private void PMProfileSettingsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PMProfileSettingsButtonMouseEntered
        PMProfileButtonPanel.setSize (140,80);
    }//GEN-LAST:event_PMProfileSettingsButtonMouseEntered

    private void PMIDTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PMIDTextBoxActionPerformed

    }//GEN-LAST:event_PMIDTextBoxActionPerformed

    private void PMEditProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PMEditProfileButtonActionPerformed
    PasswordValidation();
    
    if(checkpassword == true){
        
    try
    {
        FileInputStream fstream = new FileInputStream("ProductManager.txt");
        BufferedReader br = new BufferedReader(new InputStreamReader(fstream));
        String line = "";
        StringBuilder data = new StringBuilder();
                while ((line = br.readLine()) != null)
                {
                    String values[] = line.split(",");
                    if (values.length>0) {
                        if (values[0].equals(PMIDTextBox.getText())) {
                            String dataRow = PMIDTextBox.getText() + "," + PMUsernameTextBox.getText() + "," + PMINTextBox.getText() + ","
                            + PMPasswordTextBox.getText() + "," + PMContactTextBox.getText() + "," + PMEmailTextBox.getText() + "," + "Product Manager" + "," + "Active" + ",";
                            data.append(dataRow);
                            data.append("\n");
                        }
                        else
                        {
                            data.append(line);
                            data.append("\n");
                        }
                    }
                }
                fstream.close();
                FileWriter fw = new FileWriter("ProductManager.txt");
                BufferedWriter bw = new BufferedWriter(fw);
                bw.write(data.toString());
                bw.close();
                fw.close();
                JOptionPane.showMessageDialog(null,"Profile Modified.");
            }
            catch(IOException e)
            {
            } 
    }
        
    }//GEN-LAST:event_PMEditProfileButtonActionPerformed

    private void PMManageProductInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PMManageProductInfoMouseClicked
        ManageProductInformation PMI = new ManageProductInformation("PM");
        PMI.setVisible(true);
    }//GEN-LAST:event_PMManageProductInfoMouseClicked

    private void PMManageProductInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PMManageProductInfoMouseEntered
        PMManageProductExtPanel.setSize(150,70);
    }//GEN-LAST:event_PMManageProductInfoMouseEntered

    private void PMManageProductCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PMManageProductCategoryMouseClicked
        switchPanels (PMManageProductCategoryPanel);
    }//GEN-LAST:event_PMManageProductCategoryMouseClicked

    private void PMManageProductCategoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PMManageProductCategoryMouseEntered
        PMManageProductExtPanel.setSize (150,70);
    }//GEN-LAST:event_PMManageProductCategoryMouseEntered

    private void PMManageProductExtPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PMManageProductExtPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PMManageProductExtPanelMouseClicked

    private void PMManageProductExtPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PMManageProductExtPanelMouseEntered
        PMManageProductExtPanel.setSize(150,70);
    }//GEN-LAST:event_PMManageProductExtPanelMouseEntered

    private void PMManageProductExtPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PMManageProductExtPanelMouseExited
        PMManageProductExtPanel.setSize(0,0);
    }//GEN-LAST:event_PMManageProductExtPanelMouseExited

    private void PMManageProductButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PMManageProductButtonMouseExited
        PMManageProductExtPanel.setSize(0,0);
    }//GEN-LAST:event_PMManageProductButtonMouseExited

    private void PMManageProductInfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PMManageProductInfoMouseExited
        PMManageProductExtPanel.setSize(0,0);
    }//GEN-LAST:event_PMManageProductInfoMouseExited

    private void PMManageCatalogueButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PMManageCatalogueButtonMouseClicked
        EditCatalogueFrame ECF = new EditCatalogueFrame();
        ECF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PMManageCatalogueButtonMouseClicked

    private void PMCategoryIDTextBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PMCategoryIDTextBoxKeyTyped
        
    }//GEN-LAST:event_PMCategoryIDTextBoxKeyTyped

    private void PMCategoryIDTextBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PMCategoryIDTextBoxKeyReleased
       String queryCat = PMCategoryIDTextBox.getText();
       filterCategoryTable(queryCat);
    }//GEN-LAST:event_PMCategoryIDTextBoxKeyReleased

    private void AddCategoryButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddCategoryButtonMouseClicked
        Product p = new Product();
        EmptyValidation();
        generateCategoryID();
        
        if (checkempty == true){
            if (PMCategoryNameTextBox.getText().equals ("")){
                JOptionPane.showMessageDialog(null,"Please fill all relevant information");
            }
            else
            {
                String CategoryIDInput = PMCategoryIDTextBox.getText();
                String CategoryNameInput = PMCategoryNameTextBox.getText();
                
                p.setCategoryID(CategoryIDInput);
                p.setCategoryName(CategoryNameInput);
                p.addNewCategory();
                clearCategoryTable();
                displayCategoryTable();
        }
        }
    }//GEN-LAST:event_AddCategoryButtonMouseClicked

    private void PMCategoryNameTextBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PMCategoryNameTextBoxKeyPressed
       
    }//GEN-LAST:event_PMCategoryNameTextBoxKeyPressed

    private void PMCategoryNameTextBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PMCategoryNameTextBoxKeyTyped

    }//GEN-LAST:event_PMCategoryNameTextBoxKeyTyped

    private void ModifyCategoryButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifyCategoryButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ModifyCategoryButtonMouseClicked

    private void DeleteCategoryButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteCategoryButtonMouseClicked

    }//GEN-LAST:event_DeleteCategoryButtonMouseClicked

    private void DeleteCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteCategoryButtonActionPerformed
        String CatFilePath = "ProductCategoryData.txt";
        String catRemoveTerm = PMCategoryIDTextBox.getText();
        
        removeCAT(CatFilePath, catRemoveTerm);
    }//GEN-LAST:event_DeleteCategoryButtonActionPerformed

    private void PMCategoryNameTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PMCategoryNameTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PMCategoryNameTextBoxActionPerformed

    private void PMCategoryIDTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PMCategoryIDTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PMCategoryIDTextBoxActionPerformed

    private void ModifyCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyCategoryButtonActionPerformed
        String catcarryover = PMCategoryIDTextBox.getText();
        String id = PM.getUserID();
        new ModifyCategoryInformation(catcarryover, id).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ModifyCategoryButtonActionPerformed

    private void CategoryTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoryTableMouseClicked
        DefaultTableModel model = (DefaultTableModel)CategoryTable.getModel();
        int ProductTableRows = CategoryTable.getSelectedRow();
        PMCategoryIDTextBox.setText(model.getValueAt(ProductTableRows,0).toString());
        PMCategoryNameTextBox.setText(model.getValueAt(ProductTableRows,1).toString());
    }//GEN-LAST:event_CategoryTableMouseClicked

    private void AddCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCategoryButtonActionPerformed

    }//GEN-LAST:event_AddCategoryButtonActionPerformed

    private void PMSignoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PMSignoutButtonMouseClicked
        LoginPage LP = new LoginPage();
        this.dispose();
        LP.setVisible(true);
    }//GEN-LAST:event_PMSignoutButtonMouseClicked

    private void PMSignoutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PMSignoutButtonMouseEntered
        PMProfileButtonPanel.setSize (140, 80);
    }//GEN-LAST:event_PMSignoutButtonMouseEntered

    private void PMSignoutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PMSignoutButtonMouseExited
        PMProfileButtonPanel.setSize (0, 0);
    }//GEN-LAST:event_PMSignoutButtonMouseExited

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCategoryButton;
    private javax.swing.JTable CategoryTable;
    private javax.swing.JButton DeleteCategoryButton;
    private javax.swing.JPanel ExtendedPanel;
    private javax.swing.JLayeredPane MainPanel;
    private javax.swing.JButton ModifyCategoryButton;
    private javax.swing.JTextField PMCategoryIDTextBox;
    private javax.swing.JTextField PMCategoryNameTextBox;
    private javax.swing.JTextField PMConfirmPassword;
    private javax.swing.JTextField PMContactTextBox;
    private javax.swing.JLabel PMDashboardCloseButton;
    private javax.swing.JLabel PMDashboardMinimizeButton;
    private javax.swing.JButton PMEditProfileButton;
    private javax.swing.JTextField PMEmailTextBox;
    private javax.swing.JTextField PMIDTextBox;
    private javax.swing.JTextField PMINTextBox;
    private javax.swing.JLabel PMManageButton;
    private javax.swing.JLabel PMManageCatalogueButton;
    private javax.swing.JPanel PMManagePanel;
    private javax.swing.JLabel PMManageProductButton;
    private javax.swing.JLabel PMManageProductCategory;
    public javax.swing.JPanel PMManageProductCategoryPanel;
    private javax.swing.JPanel PMManageProductExtPanel;
    private javax.swing.JLabel PMManageProductInfo;
    private javax.swing.JTextField PMPasswordTextBox;
    private javax.swing.JLabel PMProfileButton;
    private javax.swing.JPanel PMProfileButtonPanel;
    private javax.swing.JPanel PMProfileManagementPanel;
    private javax.swing.JLabel PMProfileSettingsButton;
    private javax.swing.JLabel PMSignoutButton;
    private javax.swing.JTextField PMUsernameTextBox;
    private javax.swing.JPanel ToolbarPanel;
    private javax.swing.JLabel UsernameLabel13;
    private javax.swing.JLabel UsernameLabel5;
    private javax.swing.JLabel UsernameLabel6;
    private javax.swing.JLabel UsernameLabel7;
    private javax.swing.JLabel UsernameLabel9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
    
    private void filterCategoryTable(String queryCat){
       DefaultTableModel model = (DefaultTableModel)CategoryTable.getModel();
       TableRowSorter<DefaultTableModel> querysort = new TableRowSorter<DefaultTableModel>(model);
       CategoryTable.setRowSorter(querysort);
       querysort.setRowFilter(RowFilter.regexFilter(queryCat));
    }
    private void removeCAT(String CatFilePath, String catRemoveTerm) {
        String tempcatFile = "TempProductCategoryData.txt";
        File oldcatFile = new File(CatFilePath);
        File newcatFile = new File(tempcatFile);
        String CatID = ""; String CatName = "";
        try
        {
            FileWriter fw = new FileWriter(tempcatFile, true);
            BufferedWriter bw = new BufferedWriter(fw);
            PrintWriter pw = new PrintWriter(bw);
            Scanner sc = new Scanner(oldcatFile);
            
            sc.useDelimiter(",");
            
            while(sc.hasNext())
            {
                CatID = sc.next();
                CatName = sc.nextLine();
                if (!CatID.equals(catRemoveTerm))
                {
                    pw.println(CatID + CatName);
                }
            }
            pw.flush();
            pw.close();
            bw.close();
            fw.close();
            sc.close();
            oldcatFile.delete();
            newcatFile.renameTo(new File("ProductCategoryData.txt"));
            JOptionPane.showMessageDialog(null,"Product Removed");
            clearCategoryTable();
            displayCategoryTable();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,e.toString());
            
        }
    }
    private void generateCategoryID (){
    try
    {
        File file = new File ("ProductCategoryData.txt");
        Scanner sc = new Scanner(file);
        sc.useDelimiter(",");
        if(sc.hasNext())
        {
            String ID ="";
            while(sc.hasNext()){
                ID = sc.next();
                sc.nextLine();
        }
        String ID2 = ID.replace("CID","");         //CustomerID pass to ID and replace the words "CID" into "" and pass to ID2
        int ID3 = (Integer.parseInt(ID2))+1;        //Convert ID2 into int and + 1 and pass to ID3
        String ID4 = "CID"+String.valueOf(ID3);     //Convert ID3 into string and add "CID" and pass to ID4
        PMCategoryIDTextBox.setText(ID4);
        sc.close();
    }
        else
        {
            PMCategoryIDTextBox.setText("CID1");
        }
}
    catch (Exception e)
            {
                e.printStackTrace();
            }

}
    public  boolean EmptyValidation(){
        if(PMCategoryNameTextBox.getText() == null){
            JOptionPane.showMessageDialog(null, "There is an empty text field. Please fill in all the empty text fields.", "Empty Content", JOptionPane.WARNING_MESSAGE);
            checkempty = false;
            return false;
        }
        else{
            checkempty = true;
            return true;
        }
        
    }    
    private void getProfileDetails(){
        String checkfile = "ProductManager.txt";
        File file = new File (checkfile);
        String currentitem = PMIDTextBox.getText();
        try (Scanner sc = new Scanner(file))
        {
            sc.useDelimiter(",");
            while (sc.hasNext()){
                String ID = "";
                String Name = "";
                String IC = "";
                String Contact = "";
                String Email = "";
                
                ID = sc.next();
                Name = sc.next();
                IC = sc.next();
                sc.next();
                Contact = sc.next();
                Email = sc.next();
                sc.nextLine();

                if (ID.equals(currentitem))
                {
                    PMINTextBox.setText(IC);
                    PMUsernameTextBox.setText(Name);
                    PMContactTextBox.setText(Contact);
                    PMEmailTextBox.setText(Email);
                }
                
            }
            sc.close();
        }
        catch (Exception e)
        {
            
        }

    }
    public void PasswordValidation(){
    checkpassword = true;
    if(!PMPasswordTextBox.getText().equals(PMConfirmPassword.getText())){
        JOptionPane.showMessageDialog(null, "Please make sure your password is correct.");
        checkpassword = false;
    }
        
}
}




